
data_preprocess:
  train_days: "0-3"
  train_input_folder: "/home/vmagent/app/dataset/criteo/"
  test_input_folder: "/home/vmagent/app/dataset/criteo/"
  output_folder: "/home/vmagent/app/dataset/criteo/"
  spark_config:
    app_name: "dlrm"
    num_executors: 2
    executor_cores: 24
    executor_memory: 100GB
    scala_udf_jars: "/opt/intel/oneapi/intelpython/latest/envs/pytorch_mlperf/lib/python3.7/site-packages/ScalaProcessUtils/built/31/recdp-scala-extensions-0.1.0-jar-with-dependencies.jar"
    configs:
      spark.local.dir: '/home/vmagent/app/spark_local_dir'
      spark.driver.memory: '20G'
      spark.driver.memoryOverhead: '10G'
      spark.executor.memoryOverhead: '20G'
      spark.driver.extraClassPath: "/opt/intel/oneapi/intelpython/latest/envs/pytorch_mlperf/lib/python3.7/site-packages/ScalaProcessUtils/built/31/recdp-scala-extensions-0.1.0-jar-with-dependencies.jar"
      spark.executor.extraClassPath: "/opt/intel/oneapi/intelpython/latest/envs/pytorch_mlperf/lib/python3.7/site-packages/ScalaProcessUtils/built/31/recdp-scala-extensions-0.1.0-jar-with-dependencies.jar"

model_arguments:
  arch_sparse_feature_size: 64
  arch_dense_feature_size: 13
  arch_embedding_size: "4-3-2"
  arch_mlp_bot: "13-128-64"
  arch_mlp_top: "256-128-1"
  arch_interaction_op: "dot"
  arch_interaction_itself: False
  md_flag: False
  md_threshold: 200
  md_temperature: 0.3
  md_round_dims: False
  qr_flag: False
  qr_threshold: 200
  qr_operation: "mult"
  qr_collisions: 4
  activation_function: "relu"
  loss_function: "bce"
  loss_weights: "1.0-1.0"
  loss_threshold: 0.0
  round_targets: True
  data_size: 1
  num_batches: 0
  data_generation: "dataset"
  data_trace_file: "./input/dist_emb_j.log"
  data_set: "terabyte"
  raw_data_file: "$DATA_PATH/day"
  processed_data_file: "$DATA_PATH/terabyte_processed.npz"
  data_randomize: "total"
  data_trace_enable_padding: False
  max_ind_range: 40000000
  data_sub_sample_rate: 0.0
  num_indices_per_lookup: 10
  num_indices_per_lookup_fixed: False
  num_workers: 0
  memory_map: True
  mini_batch_size: 262144
  nepochs: 1
  learning_rate: 16
  print_precision: 5
  numpy_rand_seed: 12345
  sync_dense_params: True
  inference_only: False
  save_onnx: False
  use_gpu: False
  dist_backend: ccl
  print_freq: 16
  test_freq: 800
  test_mini_batch_size: 131072
  test_num_workers: 0
  print_time: True
  debug_mode: False
  enable_profiling: False
  plot_compute_graph: False
  profiling_start_iter: 50
  profiling_num_iters: 100
  out_dir: "."
  save_model: "./result/"
  load_model: ""
  mlperf_logging: True
  mlperf_acc_threshold: 0.0
  mlperf_auc_threshold: 0.8025
  mlperf_bin_loader: True
  mlperf_bin_shuffle: True
  lr_num_warmup_steps: 4000
  lr_decay_start_step: 5760
  lr_num_decay_steps: 27000
  sparse_dense_boundary: 1540370
  bf16: True
  use_ipex: True
  optimizer: 1
  lamblr: 30
  train_data_path: /home/vmagent/app/dataset/train_data.bin
  eval_data_path: /home/vmagent/app/dataset/test_data.bin
  day_feature_count: /home/vmagent/app/dataset/day_fea_count.npz
