@startuml RecDP class Diagram

BasePipeline <|-- FeatureWrangler
BasePipeline <|-- DataProfiler
DataProfiler --* FeatureVisualizer

BasePipeline : original_data : DataFrame 
BasePipeline : generators : [BaseFeatureGenerator[]]
BasePipeline : rdp: DataProcessor 
BasePipeline : __init__(datasets, label)
BasePipeline : fit_analyze()
BasePipeline : fit_transform(engine_type)
BasePipeline : dump_pipeline_codes()

DataProfiler : generators
DataProfiler : __init__()
DataProfiler : visualize_analyze(engine_type)

FeatureWrangler : generators
FeatureWrangler : __init__()
FeatureWrangler : fit_transform(engine_type)

FeatureVisualizer : report : html_files
FeatureVisualizer : __init__()
FeatureVisualizer : show()


' abstract        abstract
' abstract class  "abstract class"
' annotation      annotation
' circle          circle
' ()              circle_short_form
' class           class
' diamond         diamond
' <>              diamo:wnd_short_form
' entity          entity
' enum            enum
' exception       exception
' interface       interface
' protocol        protocol
' struct          struct
@enduml
