@startuml

start

:generate_pipeline_code(\n  primitiveDAG, engine_type);
if (engine_type == 'spark'?) then (yes)
    :executable = \n  _generate_pipeline_code_spark;
    :rdp = _generate_spark_engine;
else (no)
    :executable = \n  _generate_pipeline_code_pd;
    :rdp = _generate_pd_engine;
endif
:return executable;
:transformed_data = \n  rdp.executable(dataset);
:return transformed_data;
stop

@enduml
