import os, sys
import argparse

def parse_args(args):
    parser = argparse.ArgumentParser()
    # parameters will be passed to train.py by cmdlind
    # PLEASE define parameter list as below
    # saved_path is generated by hydro.ai, please use this path to save model

    # parser.add_argument('--max_depth', type=int, required=True)
    # parser.add_argument('--learning_rate', type=float, required=True)
    # ...
    #parser.add_argument('--saved_path', type=str, required=True)

    return parser.parse_args(args)

def main(params):
    # train codes
    # ...
    
    # Please save model to params.saved_path
    model_path = os.path.join(os.path.realpath(os.path.normpath(params.saved_path)), "chk000000")
    with open(model_path, 'w') as f:
        f.write(model)

    # Please return score metrics as output
    # or save result score in ${params.saved_path}/result.txt
    print(mean_accuracy)

if __name__ == '__main__':
    params = parse_args(sys.argv[1:])
    main(params)