pipeline {
    agent none
    stages {
        stage('prepare') {
            agent { 
                label 'cluster'
            }
            steps {
                cleanWs()
                checkout scm
                sh 'cd tests/cicd && docker build -t test-aidk -f Dockerfile . && docker build -t legacy-test-aidk -f DockerfileLegacy . && cd ../..'
                sh 'cd Dockerfile-ubuntu18.04 && cp /root/.ssh/id_rsa ./ && docker build -t aidk-base . -f DockerfileBase && docker build -t aidk-tensorflow . -f DockerfileTensorflow && docker build -t aidk-pytorch . -f DockerfilePytorch && docker build -t aidk-pytorch110 . -f DockerfilePytorch110 && cd ..'
            }
        }
        stage('Run pipeline_test') {
            agent { 
                label 'sr602'
            }
            steps {
                sh 'docker run --rm --privileged --network host --device=/dev/dri -v /root/cicd_logs:/home/vmagent/app/cicd_logs -v /mnt/DP_disk1/dataset:/home/vmagent/app/dataset -v `pwd`:/home/vmagent/app/hydro.ai -w /home/vmagent/app/ test-aidk /bin/bash -c "SIGOPT_API_TOKEN=$SIGOPT_API_TOKEN USE_SIGOPT=0 bash /home/vmagent/app/hydro.ai/tests/cicd/jenkins_pipeline_test.sh"'
                sh 'rm -f hydroai.db'
                sh 'rm -rf result'
            }
        }
        stage('Run minigo') {
            agent { 
                label 'sr612'
            }
            steps {
                sh 'cd modelzoo/minigo && bash patch_minigo.sh && cd ../..'
                sh 'SIGOPT_API_TOKEN=$SIGOPT_API_TOKEN USE_SIGOPT=0 bash tests/cicd/jenkins_minigo_test.sh'
                sh 'rm -f hydroai.db'
                sh 'rm -rf result'
            }
        }
        stage('Run bert') {
            agent {
                label 'sr602'
            }
            steps {
                sh 'docker run --rm --privileged --network host --device=/dev/dri -v /root/cicd_logs:/home/vmagent/app/cicd_logs -v /mnt/DP_disk1/dataset:/home/vmagent/app/dataset -v `pwd`:/home/vmagent/app/hydro.ai -w /home/vmagent/app/ test-aidk /bin/bash -c "SIGOPT_API_TOKEN=$SIGOPT_API_TOKEN USE_SIGOPT=0 bash /home/vmagent/app/hydro.ai/tests/cicd/jenkins_bert_test.sh"'
                sh 'rm -f hydroai.db'
                sh 'rm -rf result'
            }
        }
        stage('Run rnnt') {
            agent { 
                label 'sr602'
            }
            steps {
                sh 'docker run --rm --privileged --network host --device=/dev/dri -v /root/cicd_logs:/home/vmagent/app/cicd_logs -v /mnt/DP_disk1/dataset:/home/vmagent/app/dataset -v `pwd`:/home/vmagent/app/hydro.ai -w /home/vmagent/app/ test-aidk /bin/bash -c "SIGOPT_API_TOKEN=$SIGOPT_API_TOKEN USE_SIGOPT=0 bash /home/vmagent/app/hydro.ai/tests/cicd/jenkins_rnnt_test.sh"'
                sh 'rm -f hydroai.db'
                sh 'rm -rf result'
            }
        }
        stage('Run wnd') {
            agent { 
                label 'sr602'
            }
            steps {
                sh 'docker run --rm --privileged --network host --device=/dev/dri -v /root/cicd_logs:/home/vmagent/app/cicd_logs -v /mnt/DP_disk1/dataset:/home/vmagent/app/dataset -v `pwd`:/home/vmagent/app/hydro.ai -w /home/vmagent/app/ aidk-tensorflow /bin/bash -c "SIGOPT_API_TOKEN=$SIGOPT_API_TOKEN USE_SIGOPT=0 . /home/vmagent/app/hydro.ai/tests/cicd/jenkins_wnd_test.sh"'
                sh 'rm -f hydroai.db'
                sh 'rm -rf result'
            }
        }
        stage('Run dien') {
            agent { 
                label 'sr602'
            }
            steps {
                sh 'docker run --rm --privileged --network host --device=/dev/dri -v /root/cicd_logs:/home/vmagent/app/cicd_logs -v /mnt/DP_disk1/dataset:/home/vmagent/app/dataset -v `pwd`:/home/vmagent/app/hydro.ai -w /home/vmagent/app/ aidk-tensorflow /bin/bash -c "SIGOPT_API_TOKEN=$SIGOPT_API_TOKEN USE_SIGOPT=0 . /home/vmagent/app/hydro.ai/tests/cicd/jenkins_dien_test.sh"'
                sh 'rm -f hydroai.db'
                sh 'rm -rf result'
            }
        }
        stage('Run dlrm') {
            agent { 
                label 'sr602'
            }
            steps {
                sh 'docker run --rm --privileged --network host --device=/dev/dri -v /root/cicd_logs:/home/vmagent/app/cicd_logs -v /mnt/DP_disk1/dataset:/home/vmagent/app/dataset -v `pwd`:/home/vmagent/app/hydro.ai -w /home/vmagent/app/ aidk-pytorch /bin/bash -c "SIGOPT_API_TOKEN=$SIGOPT_API_TOKEN USE_SIGOPT=0 . /home/vmagent/app/hydro.ai/tests/cicd/jenkins_dlrm_test.sh"'
                sh 'rm -f hydroai.db'
                sh 'rm -rf result'
            }
        }
        stage('Run dlrm torch1.10') {
            agent { 
                label 'sr602'
            }
            steps {
                sh 'docker run --rm --privileged --network host --device=/dev/dri -v /root/cicd_logs:/home/vmagent/app/cicd_logs -v /mnt/DP_disk1/dataset:/home/vmagent/app/dataset -v `pwd`:/home/vmagent/app/hydro.ai -w /home/vmagent/app/ aidk-pytorch110 /bin/bash -c "SIGOPT_API_TOKEN=$SIGOPT_API_TOKEN USE_SIGOPT=0 . /home/vmagent/app/hydro.ai/tests/cicd/jenkins_dlrm_torch110_test.sh"'
                sh 'rm -f hydroai.db'
                sh 'rm -rf result'
            }
        }
    }
}
