pipeline {
    agent none
    stages {
        stage('Run pipeline_test') {
            agent { 
                label 'sr602'
            }
            steps {
                sh 'pwd'
                sh 'git submodule update --init --recursive'
                sh 'docker run --rm --privileged --network host --device=/dev/dri -v /root/cicd_logs:/home/vmagent/app/cicd_logs -v /mnt/DP_disk1/dataset:/home/vmagent/app/dataset -v `pwd`:/home/vmagent/app/hydro.ai -w /home/vmagent/app/ caizheng1993/oneapi-aikit:hydro.ai /bin/bash -c "SIGOPT_API_TOKEN=$SIGOPT_API_TOKEN USE_SIGOPT=0 bash /home/vmagent/app/hydro.ai/tests/cicd/jenkins_pipeline_test.sh"'
                sh 'rm -f hydroai.db'
                sh 'rm -rf result'
            }
        }
        stage('Run dien') {
            agent { 
                label 'sr602'
            }
            steps {
                sh 'docker run --rm --privileged --network host --device=/dev/dri -v /root/cicd_logs:/home/vmagent/app/cicd_logs -v /mnt/DP_disk1/dataset:/home/vmagent/app/dataset -v `pwd`:/home/vmagent/app/hydro.ai -w /home/vmagent/app/ caizheng1993/oneapi-aikit:hydro.ai /bin/bash -c "SIGOPT_API_TOKEN=$SIGOPT_API_TOKEN USE_SIGOPT=0 bash /home/vmagent/app/hydro.ai/tests/cicd/jenkins_dien_test.sh"'
                sh 'rm -f hydroai.db'
                sh 'rm -rf result'
            }
        }
        stage('Run dlrm') {
            agent { 
                label 'sr602'
            }
            steps {
                sh 'docker run --rm --entrypoint "" --privileged --network host --device=/dev/dri -v /root/cicd_logs:/home/vmagent/app/cicd_logs -v /mnt/DP_disk1/dataset:/home/vmagent/app/dataset -v `pwd`:/home/vmagent/app/hydro.ai -w /home/vmagent/app/ caizheng1993/oneapi-aikit:legacy_hydro.ai /bin/bash -c "SIGOPT_API_TOKEN=$SIGOPT_API_TOKEN USE_SIGOPT=0 bash /home/vmagent/app/hydro.ai/tests/cicd/jenkins_dlrm_test.sh"'
                sh 'rm -f hydroai.db'
                sh 'rm -rf result'
                sh 'rm -f modelzoo/dlrm/dlrm/dlrm.log'
            }
        }
        stage('Run wnd') {
            agent { 
                label 'sr602'
            }
            steps {
                sh 'docker run --rm --privileged --network host --device=/dev/dri -v /root/cicd_logs:/home/vmagent/app/cicd_logs -v /mnt/DP_disk1/dataset:/home/vmagent/app/dataset -v `pwd`:/home/vmagent/app/hydro.ai -w /home/vmagent/app/ caizheng1993/oneapi-aikit:hydro.ai /bin/bash -c "SIGOPT_API_TOKEN=$SIGOPT_API_TOKEN USE_SIGOPT=0 bash /home/vmagent/app/hydro.ai/tests/cicd/jenkins_wnd_test.sh"'
                sh 'rm -f hydroai.db'
                sh 'rm -rf result'
            }
        }
        stage('Run dlrm torch1.10') {
            agent { 
                label 'sr602'
            }
            steps {
                sh 'docker run --rm --privileged --network host --device=/dev/dri -v /root/cicd_logs:/home/vmagent/app/cicd_logs -v /mnt/DP_disk1/dataset:/home/vmagent/app/dataset -v `pwd`:/home/vmagent/app/hydro.ai -w /home/vmagent/app/ caizheng1993/oneapi-aikit:hydro.ai /bin/bash -c "SIGOPT_API_TOKEN=$SIGOPT_API_TOKEN USE_SIGOPT=0 bash /home/vmagent/app/hydro.ai/tests/cicd/jenkins_dlrm_torch110_test.sh"'
                sh 'rm -f hydroai.db'
                sh 'rm -rf result'
                sh 'rm -f modelzoo/dlrm_torch1.10/dlrm/dlrm.log'
            }
        }
    }
}
