# Process config example for dataset

# global parameters
project_name: 'demo-process'
dataset_path: '/work/e2eAIOK/RecDP/demos/data/llm-demo-dataset.jsonl'  # path to your dataset directory or file
np: 4  # number of subprocess to process your dataset

export_path: '/work/e2eAIOK/RecDP/outputs/demo-process/demo-processed.jsonl'

# process schedule
# a list of several process operators with their arguments
process:
  - sentence_split:
      lang: 'en'
  - pii_remove:
