# # Feature Vector export
bool_feature_names = ['event_weekend',
                      'user_has_already_viewed_doc']

int_feature_names = ['user_views',
                     'ad_views',
                     'doc_views',
                     'doc_event_days_since_published',
                     'doc_event_hour',
                     'doc_ad_days_since_published',
                     ]

float_feature_names = [
    'pop_ad_id',
    'pop_ad_id_conf',
    'pop_ad_id_conf_multipl',
    'pop_document_id',
    'pop_document_id_conf',
    'pop_document_id_conf_multipl',
    'pop_publisher_id',
    'pop_publisher_id_conf',
    'pop_publisher_id_conf_multipl',
    'pop_advertiser_id',
    'pop_advertiser_id_conf',
    'pop_advertiser_id_conf_multipl',
    'pop_campain_id',
    'pop_campain_id_conf',
    'pop_campain_id_conf_multipl',
    'pop_doc_event_doc_ad',
    'pop_doc_event_doc_ad_conf',
    'pop_doc_event_doc_ad_conf_multipl',
    'pop_source_id',
    'pop_source_id_conf',
    'pop_source_id_conf_multipl',
    'pop_source_id_country',
    'pop_source_id_country_conf',
    'pop_source_id_country_conf_multipl',
    'pop_entity_id',
    'pop_entity_id_conf',
    'pop_entity_id_conf_multipl',
    'pop_entity_id_country',
    'pop_entity_id_country_conf',
    'pop_entity_id_country_conf_multipl',
    'pop_topic_id',
    'pop_topic_id_conf',
    'pop_topic_id_conf_multipl',
    'pop_topic_id_country',
    'pop_topic_id_country_conf',
    'pop_topic_id_country_conf_multipl',
    'pop_category_id',
    'pop_category_id_conf',
    'pop_category_id_conf_multipl',
    'pop_category_id_country',
    'pop_category_id_country_conf',
    'pop_category_id_country_conf_multipl',
    'user_doc_ad_sim_categories',
    'user_doc_ad_sim_categories_conf',
    'user_doc_ad_sim_categories_conf_multipl',
    'user_doc_ad_sim_topics',
    'user_doc_ad_sim_topics_conf',
    'user_doc_ad_sim_topics_conf_multipl',
    'user_doc_ad_sim_entities',
    'user_doc_ad_sim_entities_conf',
    'user_doc_ad_sim_entities_conf_multipl',
    'doc_event_doc_ad_sim_categories',
    'doc_event_doc_ad_sim_categories_conf',
    'doc_event_doc_ad_sim_categories_conf_multipl',
    'doc_event_doc_ad_sim_topics',
    'doc_event_doc_ad_sim_topics_conf',
    'doc_event_doc_ad_sim_topics_conf_multipl',
    'doc_event_doc_ad_sim_entities',
    'doc_event_doc_ad_sim_entities_conf',
    'doc_event_doc_ad_sim_entities_conf_multipl'
]

TRAFFIC_SOURCE_FV = 'traffic_source'
EVENT_HOUR_FV = 'event_hour'
EVENT_COUNTRY_FV = 'event_country'
EVENT_COUNTRY_STATE_FV = 'event_country_state'
EVENT_GEO_LOCATION_FV = 'event_geo_location'
EVENT_PLATFORM_FV = 'event_platform'
AD_ADVERTISER_FV = 'ad_advertiser'
DOC_AD_SOURCE_ID_FV = 'doc_ad_source_id'
DOC_AD_PUBLISHER_ID_FV = 'doc_ad_publisher_id'
DOC_EVENT_SOURCE_ID_FV = 'doc_event_source_id'
DOC_EVENT_PUBLISHER_ID_FV = 'doc_event_publisher_id'
DOC_AD_CATEGORY_ID_FV = 'doc_ad_category_id'
DOC_AD_TOPIC_ID_FV = 'doc_ad_topic_id'
DOC_AD_ENTITY_ID_FV = 'doc_ad_entity_id'
DOC_EVENT_CATEGORY_ID_FV = 'doc_event_category_id'
DOC_EVENT_TOPIC_ID_FV = 'doc_event_topic_id'
DOC_EVENT_ENTITY_ID_FV = 'doc_event_entity_id'

# ### Configuring feature vector
category_feature_names_integral = ['ad_advertiser',
                                   'doc_ad_category_id_1',
                                   'doc_ad_category_id_2',
                                   'doc_ad_category_id_3',
                                   'doc_ad_topic_id_1',
                                   'doc_ad_topic_id_2',
                                   'doc_ad_topic_id_3',
                                   'doc_ad_entity_id_1',
                                   'doc_ad_entity_id_2',
                                   'doc_ad_entity_id_3',
                                   'doc_ad_entity_id_4',
                                   'doc_ad_entity_id_5',
                                   'doc_ad_entity_id_6',
                                   'doc_ad_publisher_id',
                                   'doc_ad_source_id',
                                   'doc_event_category_id_1',
                                   'doc_event_category_id_2',
                                   'doc_event_category_id_3',
                                   'doc_event_topic_id_1',
                                   'doc_event_topic_id_2',
                                   'doc_event_topic_id_3',
                                   'doc_event_entity_id_1',
                                   'doc_event_entity_id_2',
                                   'doc_event_entity_id_3',
                                   'doc_event_entity_id_4',
                                   'doc_event_entity_id_5',
                                   'doc_event_entity_id_6',
                                   'doc_event_publisher_id',
                                   'doc_event_source_id',
                                   'event_country',
                                   'event_country_state',
                                   'event_geo_location',
                                   'event_hour',
                                   'event_platform',
                                   'traffic_source']

feature_vector_labels_integral = bool_feature_names \
                                 + int_feature_names \
                                 + float_feature_names \
                                 + category_feature_names_integral



integral_headers = ['label', 'display_id', 'ad_id', 'doc_id', 'doc_event_id',
                    'is_leak'] + feature_vector_labels_integral

CSV_ORDERED_COLUMNS = ['label', 'display_id', 'ad_id', 'doc_id', 'doc_event_id', 'is_leak', 'event_weekend',
                       'user_has_already_viewed_doc', 'user_views', 'ad_views', 'doc_views',
                       'doc_event_days_since_published', 'doc_event_hour', 'doc_ad_days_since_published',
                       'pop_ad_id', 'pop_ad_id_conf',
                       'pop_ad_id_conf_multipl', 'pop_document_id', 'pop_document_id_conf',
                       'pop_document_id_conf_multipl', 'pop_publisher_id', 'pop_publisher_id_conf',
                       'pop_publisher_id_conf_multipl', 'pop_advertiser_id', 'pop_advertiser_id_conf',
                       'pop_advertiser_id_conf_multipl', 'pop_campain_id', 'pop_campain_id_conf',
                       'pop_campain_id_conf_multipl', 'pop_doc_event_doc_ad', 'pop_doc_event_doc_ad_conf',
                       'pop_doc_event_doc_ad_conf_multipl', 'pop_source_id', 'pop_source_id_conf',
                       'pop_source_id_conf_multipl', 'pop_source_id_country', 'pop_source_id_country_conf',
                       'pop_source_id_country_conf_multipl', 'pop_entity_id', 'pop_entity_id_conf',
                       'pop_entity_id_conf_multipl', 'pop_entity_id_country', 'pop_entity_id_country_conf',
                       'pop_entity_id_country_conf_multipl', 'pop_topic_id', 'pop_topic_id_conf',
                       'pop_topic_id_conf_multipl', 'pop_topic_id_country', 'pop_topic_id_country_conf',
                       'pop_topic_id_country_conf_multipl', 'pop_category_id', 'pop_category_id_conf',
                       'pop_category_id_conf_multipl', 'pop_category_id_country', 'pop_category_id_country_conf',
                       'pop_category_id_country_conf_multipl', 'user_doc_ad_sim_categories',
                       'user_doc_ad_sim_categories_conf', 'user_doc_ad_sim_categories_conf_multipl',
                       'user_doc_ad_sim_topics', 'user_doc_ad_sim_topics_conf', 'user_doc_ad_sim_topics_conf_multipl',
                       'user_doc_ad_sim_entities', 'user_doc_ad_sim_entities_conf',
                       'user_doc_ad_sim_entities_conf_multipl',
                       'doc_event_doc_ad_sim_categories', 'doc_event_doc_ad_sim_categories_conf',
                       'doc_event_doc_ad_sim_categories_conf_multipl', 'doc_event_doc_ad_sim_topics',
                       'doc_event_doc_ad_sim_topics_conf', 'doc_event_doc_ad_sim_topics_conf_multipl',
                       'doc_event_doc_ad_sim_entities', 'doc_event_doc_ad_sim_entities_conf',
                       'doc_event_doc_ad_sim_entities_conf_multipl', 'ad_advertiser', 'doc_ad_category_id_1',
                       'doc_ad_category_id_2', 'doc_ad_category_id_3', 'doc_ad_topic_id_1', 'doc_ad_topic_id_2',
                       'doc_ad_topic_id_3', 'doc_ad_entity_id_1', 'doc_ad_entity_id_2', 'doc_ad_entity_id_3',
                       'doc_ad_entity_id_4', 'doc_ad_entity_id_5', 'doc_ad_entity_id_6', 'doc_ad_publisher_id',
                       'doc_ad_source_id', 'doc_event_category_id_1', 'doc_event_category_id_2',
                       'doc_event_category_id_3',
                       'doc_event_topic_id_1', 'doc_event_topic_id_2', 'doc_event_topic_id_3', 'doc_event_entity_id_1',
                       'doc_event_entity_id_2', 'doc_event_entity_id_3', 'doc_event_entity_id_4',
                       'doc_event_entity_id_5',
                       'doc_event_entity_id_6', 'doc_event_publisher_id', 'doc_event_source_id', 'event_country',
                       'event_country_state', 'event_geo_location', 'event_hour', 'event_platform', 'traffic_source']

FEAT_CSV_ORDERED_COLUMNS = ['event_weekend',
                            'user_has_already_viewed_doc', 'user_views', 'ad_views', 'doc_views',
                            'doc_event_days_since_published', 'doc_event_hour', 'doc_ad_days_since_published',
                            'pop_ad_id', 'pop_ad_id_conf',
                            'pop_ad_id_conf_multipl', 'pop_document_id', 'pop_document_id_conf',
                            'pop_document_id_conf_multipl', 'pop_publisher_id', 'pop_publisher_id_conf',
                            'pop_publisher_id_conf_multipl', 'pop_advertiser_id', 'pop_advertiser_id_conf',
                            'pop_advertiser_id_conf_multipl', 'pop_campain_id', 'pop_campain_id_conf',
                            'pop_campain_id_conf_multipl', 'pop_doc_event_doc_ad', 'pop_doc_event_doc_ad_conf',
                            'pop_doc_event_doc_ad_conf_multipl', 'pop_source_id', 'pop_source_id_conf',
                            'pop_source_id_conf_multipl', 'pop_source_id_country', 'pop_source_id_country_conf',
                            'pop_source_id_country_conf_multipl', 'pop_entity_id', 'pop_entity_id_conf',
                            'pop_entity_id_conf_multipl', 'pop_entity_id_country', 'pop_entity_id_country_conf',
                            'pop_entity_id_country_conf_multipl', 'pop_topic_id', 'pop_topic_id_conf',
                            'pop_topic_id_conf_multipl', 'pop_topic_id_country', 'pop_topic_id_country_conf',
                            'pop_topic_id_country_conf_multipl', 'pop_category_id', 'pop_category_id_conf',
                            'pop_category_id_conf_multipl', 'pop_category_id_country', 'pop_category_id_country_conf',
                            'pop_category_id_country_conf_multipl', 'user_doc_ad_sim_categories',
                            'user_doc_ad_sim_categories_conf', 'user_doc_ad_sim_categories_conf_multipl',
                            'user_doc_ad_sim_topics', 'user_doc_ad_sim_topics_conf',
                            'user_doc_ad_sim_topics_conf_multipl',
                            'user_doc_ad_sim_entities', 'user_doc_ad_sim_entities_conf',
                            'user_doc_ad_sim_entities_conf_multipl',
                            'doc_event_doc_ad_sim_categories', 'doc_event_doc_ad_sim_categories_conf',
                            'doc_event_doc_ad_sim_categories_conf_multipl', 'doc_event_doc_ad_sim_topics',
                            'doc_event_doc_ad_sim_topics_conf', 'doc_event_doc_ad_sim_topics_conf_multipl',
                            'doc_event_doc_ad_sim_entities', 'doc_event_doc_ad_sim_entities_conf',
                            'doc_event_doc_ad_sim_entities_conf_multipl', 'ad_advertiser', 'doc_ad_category_id_1',
                            'doc_ad_category_id_2', 'doc_ad_category_id_3', 'doc_ad_topic_id_1', 'doc_ad_topic_id_2',
                            'doc_ad_topic_id_3', 'doc_ad_entity_id_1', 'doc_ad_entity_id_2', 'doc_ad_entity_id_3',
                            'doc_ad_entity_id_4', 'doc_ad_entity_id_5', 'doc_ad_entity_id_6', 'doc_ad_publisher_id',
                            'doc_ad_source_id', 'doc_event_category_id_1', 'doc_event_category_id_2',
                            'doc_event_category_id_3',
                            'doc_event_topic_id_1', 'doc_event_topic_id_2', 'doc_event_topic_id_3',
                            'doc_event_entity_id_1',
                            'doc_event_entity_id_2', 'doc_event_entity_id_3', 'doc_event_entity_id_4',
                            'doc_event_entity_id_5',
                            'doc_event_entity_id_6', 'doc_event_publisher_id', 'doc_event_source_id', 'event_country',
                            'event_country_state', 'event_geo_location', 'event_hour', 'event_platform',
                            'traffic_source']

CONVERT_TO_INT = ['doc_ad_category_id_1',
                  'doc_ad_category_id_2', 'doc_ad_category_id_3', 'doc_ad_topic_id_1', 'doc_ad_topic_id_2',
                  'doc_ad_topic_id_3', 'doc_ad_entity_id_1', 'doc_ad_entity_id_2', 'doc_ad_entity_id_3',
                  'doc_ad_entity_id_4', 'doc_ad_entity_id_5', 'doc_ad_entity_id_6',
                  'doc_ad_source_id', 'doc_event_category_id_1', 'doc_event_category_id_2', 'doc_event_category_id_3',
                  'doc_event_topic_id_1', 'doc_event_topic_id_2', 'doc_event_topic_id_3', 'doc_event_entity_id_1',
                  'doc_event_entity_id_2', 'doc_event_entity_id_3', 'doc_event_entity_id_4', 'doc_event_entity_id_5',
                  'doc_event_entity_id_6']
