# Copyright (c) 2019-2020, NVIDIA CORPORATION. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM xuechendi/oneapi-aikit:hydro.ai

ENV PATH /opt/intel/oneapi/intelpython/python3.7/condabin:$PATH
RUN /bin/bash -c "source ~/.bashrc && conda init bash && conda activate pytorch"
# RUN /bin/bash -c "conda activate pytorch"
# ENV PATH /opt/intel/oneapi/intelpython/python3.7/condabin:$PATH
# RUN conda init bash && \
#     conda activate pytorch

RUN apt install -y sox

COPY requirements.txt .
RUN pip install --no-cache --disable-pip-version-check -U -r requirements.txt

RUN git clone https://github.com/HawkAaron/warp-transducer && \
    cd warp-transducer && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make && \
    cd ../pytorch_binding && \
    python setup.py install && \
    cd ../../..

WORKDIR /workspace/rnnt

RUN pip install torch_optimizer==0.1.0

RUN pip install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-cuda110
