experiment:
  project: "baselines"
  tag: "cifar100_denascnn"
  model_save: "/home/vmagent/app/data/model"
dataset:
  type: "cifar100"
  num_workers: 4
  path: "/home/vmagent/app/data/dataset"
model:
  type: "denas_cnn"
  # pretrain: "/home/vmagent/app/data/model/baselines/cifar100_denascnn/backbone_best.pth"
solver:
  batch_size: 128
  epochs: 200
  optimizer:
    type: "SGD"
    lr: 0.1
    weight_decay: 5e-4
    momentum: 0.9
  scheduler:
    type: "MultiStepLR"
    lr_decay_rate: 0.2
    MultiStepLR:
      lr_decay_stages: [60, 120, 160]
  early_stop:
    flag: False