name: Dev PR

on:

  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  process:
    name: Process
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test cmd
        run: |
            echo "wow"
