name: Publish E2EAIOK Deltatuner nightly to PyPI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'e2eAIOK/deltatuner/version'


jobs:
  e2eaiok-dtuner-nightly-python-pypi:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Build sdist
      run: |
        pip install build wheel
        cd e2eAIOK/deltatuner
        release_version=$(cat deltatuner/version | head -1)
        nightly_build_date=`date '+%Y%m%d%H%M'`
        nightly_version=${release_version}b${nightly_build_date}
        echo $nightly_version > deltatuner/version
        python3 setup.py sdist

    - name: Upload
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: e2eAIOK/deltatuner/dist
        verbose: true
