name: Publish e2eAIOK-sda Stable Release to PyPI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'e2eAIOK/version'

permissions:
  contents: read
  packages: write

jobs:
  e2eaiok-release-python-pypi:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'intel' }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Build Package
      run: |
        pip install build wheel
        python3 setup.py bdist_wheel --sda

    - name: Upload Package
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}