name: Integration Test Workload DIEN

on:
  pull_request:
    branches:
    - main

jobs:
  integration_test:
    name: Integration Test Workload DIEN
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build Docker
      run: |
        cd Dockerfile-ubuntu18.04 && docker build -t e2eaiok-tensorflow . -f DockerfileTensorflow && cd .. && yes | docker container prune && yes | docker image prune

    - name: Test DIEN
      run: |
        cd modelzoo/dien/train && bash patch_dien.sh && cd ../../..
        docker run --rm --name test-workload-dien --privileged --network host --device=/dev/dri -v /mnt/DP_disk1/dataset:/home/vmagent/app/dataset -v `pwd`:/home/vmagent/app/e2eaiok -w /home/vmagent/app/ e2eaiok-tensorflow /bin/bash -c "USE_SIGOPT=0 . /home/vmagent/app/e2eaiok/tests/cicd/jenkins_dien_test.sh"