name: Integration Test Workload DIEN

on:
  pull_request:
    branches:
    - main
    paths:
    - '.github/workflows/integration_test_workload_dien.yml'
    - 'conf/e2eaiok_defaults_dien_example.conf'
    - 'demo/builtin/dien/**'
    - 'Dockerfile-ubuntu/DockerfileTensorflow'
    - 'e2eAIOK/SDA/**'
    - 'e2eAIOK/common/**'
    - 'e2eAIOK/dataloader/**'
    - 'e2eAIOK/utils/**'
    - 'modelzoo/dien/**'
    - 'tests/cicd/conf/**'
    - 'tests/cicd/src/**'
    - 'tests/cicd/test_*.bats'
    - 'tests/cicd/Jenkinsfile*'
    - 'tests/cicd/jenkins_dien_test*.sh'

jobs:
  integration_test:
    name: Integration Test Workload DIEN
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build Docker
      run: |
        cd Dockerfile-ubuntu && docker build -t e2eaiok-tensorflow . -f DockerfileTensorflow && cd .. && yes | docker container prune && yes | docker image prune

    - name: Test DIEN
      run: |
        if [[ $(docker ps -q --filter "name=test-workload-dien" | wc -l) -ne 0 ]]; then docker ps -q --filter "name=test-workload-dien" | grep -q . && docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q); fi
        cd modelzoo/dien/train && bash patch_dien.sh && cd ../../..
        docker run --rm --name test-workload-dien --privileged --network host --device=/dev/dri -v /mnt/DP_disk1/dataset:/home/vmagent/app/dataset -v `pwd`:/home/vmagent/app/e2eaiok -w /home/vmagent/app/ e2eaiok-tensorflow /bin/bash -c "USE_SIGOPT=0 . /home/vmagent/app/e2eaiok/tests/cicd/jenkins_dien_test.sh"