name: Integration Test DeNas ASR

on:
  pull_request:
    branches:
    - main
    paths:
    - '.github/workflows/integration_test_denas_asr.yml'
    - 'conf/denas/asr/**'
    - 'demo/denas/asr/**'
    - 'Dockerfile-ubuntu18.04/DockerfilePytorch112'
    - 'e2eAIOK/DeNas/**'
    - 'e2eAIOK/common/**'
    - 'e2eAIOK/dataloader/**'
    - 'e2eAIOK/utils/**'
    - 'tests/cicd/**'


jobs:
  integration_test:
    name: Integration Test DeNas ASR
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build Docker
      run: |
        cd Dockerfile-ubuntu18.04 && docker build -t e2eaiok-pytorch112 . -f DockerfilePytorch112 && cd .. && yes | docker container prune && yes | docker image prune

    - name : Test ASR
      run: |
        if [[ $(docker ps -q --filter "name=test-denas-asr" | wc -l) -ne 0 ]]; then docker ps -q --filter "name=test-denas-asr" | grep -q . && docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q); fi
        docker run --rm --name test-denas-asr --shm-size=10g --privileged --network host --device=/dev/dri -v /mnt/DP_disk1/dataset/LibriSpeech-denas:/home/vmagent/app/dataset/LibriSpeech -v `pwd`:/home/vmagent/app/e2eaiok -w /home/vmagent/app/ e2eaiok-pytorch112 /bin/bash -c ". /home/vmagent/app/e2eaiok/tests/cicd/jenkins_denas_asr.sh"