name: Integration Test Model Adapter domain adapter

on:
  pull_request:
    branches:
    - main
    paths:
    - '.github/workflows/integration_test_ma_adapter.yml'
    - 'Dockerfile-ubuntu/DockerfilePytorch112'
    - 'e2eAIOK/ModelAdapter/**'
    - 'tests/cicd/ModelAdapterJenkinsfile'
    - 'tests/cicd/jenkins_ma_adapter_test.sh'
    - 'modelzoo/unet/**'

jobs:
  integration_test:
    name: Integration Test Model Adapter domain adapter
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build Docker
      run: |
        cd Dockerfile-ubuntu && docker build -t e2eaiok-pytorch112 . -f DockerfilePytorch112 && cd .. && yes | docker container prune && yes | docker image prune

    - name : Test Model Adapter domain adapter
      run: |
        if [[ $(docker ps -q --filter "name=test-ma-adapter" | wc -l) -ne 0 ]]; then docker ps -q --filter "name=test-ma-adapter" | grep -q . && docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q); fi
        docker run --rm --name test-ma-adapter --shm-size=100g --privileged --network host --device=/dev/dri -v /mnt/DP_disk1/dataset:/home/vmagent/app/data  -v `pwd`:/home/vmagent/app/e2eaiok -w /home/vmagent/app/ e2eaiok-pytorch112 /bin/bash -c ". /home/vmagent/app/e2eaiok/tests/cicd/jenkins_ma_adapter_test.sh"