name: Publish e2eAIOK Docker PyTorch1.12

on:
  pull_request:
    branches:
      - main
    paths:
      - 'e2eAIOK/version'
      - 'Dockerfile-ubuntu18.04/DockerfilePytorch'
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'e2eAIOK/version'
      - 'Dockerfile-ubuntu18.04/DockerfilePytorch112'

jobs:
  e2eaiok-release-docker:
    runs-on: sr602
    if: ${{ github.repository_owner == 'intel' }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Set up Release Version
        run: |
          echo RELEASE_VERSION=$(cat e2eAIOK/version | head -1) >> $GITHUB_ENV
      -
        name: Build and Push Docker images
        uses: docker/build-push-action@v3
        with:
          context: ./Dockerfile-ubuntu18.04
          file: ./Dockerfile-ubuntu18.04/DockerfilePytorch112
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/e2eaiok-pytorch112:${{ env.RELEASE_VERSION }}