name: Unittest AutoFE
on:
  pull_request:
    branches:
    - main
    paths:
    - 'RecDP/pyrecdp/autofe/**'
    - 'RecDP/pyrecdp/core/**'
    - 'RecDP/pyrecdp/primitives/estimators/**'
    - 'RecDP/pyrecdp/primitives/generators/**'
    - 'RecDP/pyrecdp/primitives/operations/**'
    - 'RecDP/pyrecdp/primitives/profilers/**'
    - 'RecDP/tests/cicd/bashrun_unittest_autofe.sh'
    - 'RecDP/tests/test_autofe.py'

jobs:
  unittest:
    name: Unittest AutoFE
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Docker
      run: |
        cd RecDP && cd Dockerfile && docker build -t pyrecdp-test-env . -f DockerfileUbuntu --build-arg https_proxy=${https_proxy} && cd .. && yes | docker container prune && yes | docker image prune 

    - name: RUN Unittests
      run: |
        cd RecDP && docker run --rm --name unittest-pyrecdp-autofe-pandas --shm-size=100g --privileged --network host --device=/dev/dri -v `pwd`:/home/vmagent/app/ -w /home/vmagent/app/ pyrecdp-test-env /bin/bash -c "sh tests/cicd/bashrun_unittest_autofe.sh"